# Generated by Django 5.0.6 on 2024-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="type",
            field=models.CharField(
                choices=[("family", "Family"), ("friends", "Friends")], max_length=255
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("restaurant", "number")},
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=2)),
                ("description", models.TextField(blank=True, null=True)),
                ("categories", models.ManyToManyField(to="system.category")),
            ],
        ),
        migrations.AddField(
            model_name="restaurant",
            name="dishes",
            field=models.ManyToManyField(to="system.dish"),
        ),
    ]
