# Generated by Django 5.0.6 on 2024-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_alter_table_type_alter_table_unique_together_dish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
