# Generated by Django 5.0.6 on 2024-07-03 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_remove_table_type_table_description_table_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="chairs",
        ),
    ]
