# Generated by Django 5.0.6 on 2024-07-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_remove_table_chairs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
