# Generated by Django 5.0.6 on 2024-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_dish_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests_number",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
