# Generated by Django 5.0.6 on 2024-07-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_restaurant_lat_restaurant_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="work_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="work_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
