# Generated by Django 5.0.6 on 2024-07-10 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_restaurant_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("customer", "restaurant")},
        ),
    ]
