# Generated by Django 5.0.6 on 2024-07-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_alter_review_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
