# Generated by Django 5.0.6 on 2024-11-01 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0017_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.DeleteModel(
            name="ParentCategory",
        ),
    ]
